package com.example.beatopoc

import android.app.ProgressDialog
import android.graphics.Color
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import androidx.databinding.DataBindingUtil
import com.example.beatopoc.databinding.ActivityLeadIitestBinding
import `in`.sunfox.healthcare.commons.android.spandan_sdk.OnApiReportGenerationListener
import `in`.sunfox.healthcare.commons.android.spandan_sdk.SpandanSDK
import `in`.sunfox.healthcare.commons.android.spandan_sdk.collection.EcgTest
import `in`.sunfox.healthcare.commons.android.spandan_sdk.collection.EcgTestCallback
import `in`.sunfox.healthcare.commons.android.spandan_sdk.conclusion.EcgReport
import `in`.sunfox.healthcare.commons.android.spandan_sdk.connection.DeviceInfo
import `in`.sunfox.healthcare.commons.android.spandan_sdk.connection.OnDeviceConnectionStateChangeListener
import `in`.sunfox.healthcare.commons.android.spandan_sdk.enums.DeviceConnectionState
import `in`.sunfox.healthcare.commons.android.spandan_sdk.enums.EcgPosition
import `in`.sunfox.healthcare.commons.android.spandan_sdk.enums.EcgTestType
import `in`.sunfox.healthcare.commons.android.spandan_sdk.retrofit_helper.EcgApiResult
import `in`.sunfox.healthcare.commons.android.spandan_sdk.retrofit_helper.EcgReportApiInput
import com.example.beatopoc.Helper.convertListToBase64String


class LeadIITestActivity : AppCompatActivity(), EcgTestCallback,
    OnDeviceConnectionStateChangeListener {
    private lateinit var binding: ActivityLeadIitestBinding
    private lateinit var spandanSDK: SpandanSDK
    private var ecgPoints: HashMap<EcgPosition, ArrayList<Double>> = hashMapOf()
    private var ecgReport: EcgReport? = null
    private var ecgApiResult:EcgApiResult?=null
    private lateinit var ecgTest: EcgTest
    private lateinit var ecgPosition: EcgPosition
    private lateinit var progressDialog: ProgressDialog

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView(this, R.layout.activity_lead_iitest)

        binding.activityMainTextviewCurrentPosition.text = "Please select the lead"

        progressDialog = ProgressDialog(this)
        try {
            spandanSDK = SpandanSDK.getInstance()

            /**
             * step :-2
             * set callback for device connectivity.*/
            spandanSDK.setOnDeviceConnectionStateChangedListener(this)
            /**
             * step :-3
             * create ecg test..*/
            ecgTest = spandanSDK.createTest(
                EcgTestType.LEAD_TWO, this
                , (application as ApplicationClass).token!!
            )


            binding.activityMainLayoutDeviceConnectionStatus.setBackgroundColor(if (SpandanSDK.getInstance().isDeviceConnected()) Color.GREEN else Color.RED)


            binding.progressBar8.setOnClickListener {
                //ecgPosition = EcgPosition.LEAD_2
                //binding.activityMainTextviewCurrentPosition.text = EcgPosition.LEAD_2.name
            }

            /***
             * step :-4
             * start ecg test.*/
            binding.activityMainBtnStartTest.setOnClickListener {
                ecgPosition = EcgPosition.LEAD_2
                binding.activityMainTextviewCurrentPosition.text = EcgPosition.LEAD_2.name

                if (!SpandanSDK.getInstance().isDeviceConnected())
                    Toast.makeText(this, "Please connect the device first.", Toast.LENGTH_SHORT)
                        .show()
                else if (!::ecgPosition.isInitialized)
                    Toast.makeText(this, "please select any lead", Toast.LENGTH_SHORT).show()
                else
                    ecgTest.start(ecgPosition)
            }


            /**
             * step :-5
             * generate ecg report*/
            binding.activityMainBtnGenerateReport.setOnClickListener {
                Log.d("SdkImpl.TAG", "onCreate: impl $ecgPoints")
                showProgressDialog()
//                spandanSDK.generateReport(12,
//                    ecgPoints,
//                    (application as BeatoApplication).token!!,
//                    object : OnReportGenerationStateListener {
//                        override fun onReportGenerationSuccess(ecgReport: EcgReport,pdfInputStream: InputStream?) {
//                            this@LeadIITestActivity.ecgReport = ecgReport
//                            binding.result.text = (ecgReport.conclusion as LeadTwoConclusion).detection
//                            runOnUiThread {
//                                pdfInputStream?.let {
//                                    val folder = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).absolutePath
//                                    val file = File(folder,"myPdf.pdf")
//                                    file.createNewFile()
//                                    val fileOutputStream = FileOutputStream(file)
//                                    val buffer = ByteArray(4*1024)
//                                    while (true){
//                                        val byteCount = it.read(buffer)
//                                        if (byteCount<0) break
//                                        fileOutputStream.write(buffer,0,byteCount)
//                                    }
//                                    Log.d("Debug.TAG", "onReportGenerationSuccess: ${it.available()}")
//                                    Toast.makeText(this@LeadIITestActivity,
//                                        "report generated::: ->>>>> ${it.available()}",
//                                        Toast.LENGTH_SHORT).show()
//                                }
////                                Toast.makeText(this@LeadIITestActivity,
////                                    "report generated",
////                                    Toast.LENGTH_SHORT).show()
//                            }
//                        }
//
//                        override fun onReportGenerationFailed(errorCode: Int, errorMsg: String) {
//                            Log.d("SdkImpl.TAG", "onReportGenerationFailed: $errorMsg")
//                            runOnUiThread {
//                                Toast.makeText(this@LeadIITestActivity, errorMsg, Toast.LENGTH_SHORT)
//                                    .show()
//                            }
//                        }
//
//                    })
                val encode = convertListToBase64String(ecgPoints[EcgPosition.LEAD_2]!!)
                spandanSDK.generateReportWithPdf( verifierKey = "enter verifier token", apiKey =  "enter api key",
                    ecgReportApiInput = EcgReportApiInput(
                        age = "34",
                        first_name = "first",
                        last_name = "last",
                        gender = "Male",
                        generate_pdf_report = true,
                        height = "147",
                        weight = "60",
                        lead2_data = encode,
                        processor_type = "LEAD_TWO"
                    ),
                    onApiReportGenerationListener = object :
                        OnApiReportGenerationListener {
                        override fun onReportGenerationSuccess(ecgReport: EcgApiResult) {
                            this@LeadIITestActivity.ecgApiResult = ecgReport
                            runOnUiThread {
                                hideProgressDialog()
                                binding.pdfLinkUrl.text = ecgReport.url
                            }
                        }

                        override fun onReportGenerationFailed(errorMsg: String) {
                            runOnUiThread {
                                hideProgressDialog()
                                binding.pdfLinkUrl.text = errorMsg
                            }
                        }
                    })
            }


            binding.activityMainBtnShowConclusion.setOnClickListener {
//                ecgReport?.let {
                ecgApiResult?.let {
//                    val conclusion = (ecgReport?.conclusion as LeadTwoConclusion)
//                    val characteristics = ecgReport?.ecgCharacteristics
//                    binding.result.text = "$conclusion $characteristics"
//                    val conclusion = (ecgApiResult?.conclusions as LeadTwoConclusion)
                    val conclusion = (ecgApiResult?.conclusions)
                    val characteristics = ecgApiResult?.characteristics
                    binding.result.text = "$conclusion $characteristics"
                }
            }
        } catch (e: Exception) {
            Toast.makeText(this, e.message, Toast.LENGTH_SHORT).show()
        }
    }

    private fun showProgressDialog() {
        progressDialog.setTitle("Please wait")
        progressDialog.setMessage("Generating report....")
        progressDialog.setCanceledOnTouchOutside(false)
        progressDialog.show()
    }

    private fun hideProgressDialog(){
        progressDialog.dismiss()
    }

    override fun onTestFailed(statusCode: Int) {
        Toast.makeText(this, "onTestFailed $statusCode", Toast.LENGTH_SHORT).show()
    }

    override fun onTestStarted(ecgPosition: EcgPosition) {
        Log.d("SdkImpl.TAG", "onTestStarted: ")
        Toast.makeText(this@LeadIITestActivity, "test started", Toast.LENGTH_SHORT)
            .show()
    }

    override fun onElapsedTimeChanged(elapsedTime: Long, remainingTime: Long) {
        binding.activityMainProgressbarTestStatus.progress = elapsedTime.toInt()
        binding.progressBar8.progress = elapsedTime.toInt()
    }

    override fun onReceivedData(data: String) {
        Log.d("SdkImpl.TAG", "onReceivedData: $data")
        runOnUiThread {
            binding.activityMainTextviewTestStatus.text = data
        }
    }

    //    private fun convertDoubleArrayListToByteArray(doubleArrayList: ArrayList<Double>): ByteArray {
//        // Convert the list of Doubles to a ByteArray using ByteBuffer
//        val byteBuffer = ByteBuffer.allocate(doubleArrayList.size * 8)
//        for (value in doubleArrayList) {
//            byteBuffer.putDouble(value)
//        }
//        return byteBuffer.array()
//    }

    override fun onPositionRecordingComplete(
        ecgPosition: EcgPosition,
        ecgPoints: ArrayList<Double>?,
    ) {
        this.ecgPoints.set(ecgPosition, ecgPoints!!)
        Toast.makeText(this, "${ecgPoints?.size}", Toast.LENGTH_SHORT).show()

//        val pointsString = StringBuilder()
//        ecgPoints.forEachIndexed { index, d ->
//            if (index != ecgPoints.lastIndex)
//                pointsString.append("$d,")
//            else
//                pointsString.append(d)
//        }

//                    val byteArray = Helper.convertDoubleArrayListToByteArray(ecgPoints!!)
//
//                    // Step 2: Encode byte array to Base64
//                    val base64String = Helper.encodeToBase64(byteArray)
//                    val data = RetrofitHelper().getRetrofitInstance1().getReport(
//                        (EcgProcessorInput(
//                            lead2_data= "NTI5LDUyOCw1MjgsNTI3LDUyNiw1MjYsNTI2LDUyNiw1MjcsNTMwLDUzMyw1MzQsNTM1LDUzNCw1MzQsNTMyLDUzMCw1MjgsNTI1LDUyMiw1MTksNTE1LDUxNSw1MTQsNTE1LDUxNCw1MTgsNTE3LDUxOSw1MjQsNTI4LDUzMSw1MzEsNTMyLDUzMiw1MzAsNTMwLDUzMCw1MzEsNTMyLDUzNCw1MzgsNTQyLDU0Niw1NTAsNTUyLDU1Myw1NTMsNTU1LDU1Niw1NTYsNTU1LDU1NCw1NTUsNTU4LDU2Miw1NjcsNTcyLDU3Niw1NzYsNTc4LDU3OCw1ODAsNTgwLDU4NCw1ODksNTk0LDU5Nyw2MDAsNTk4LDU5NSw1OTQsNTk1LDU5Niw1OTgsNjAyLDYwOCw2MTQsNjE4LDYyMSw2MjMsNjI0LDYyNiw2MjgsNjI5LDYzMCw2MjksNjI2LDYyMSw2MTYsNjEyLDYwOSw2MDgsNjA2LDYwNyw2MDgsNjA4LDYwNyw2MDUsNjAxLDU5Nyw1OTIsNTg2LDU4MSw1NzQsNTY3LDU2Miw1NTUsNTQ4LDUzOSw1MzIsNTI1LDUyMCw1MTUsNTEyLDUwOCw1MDMsNDk4LDQ5NCw0ODgsNDgzLDQ3Niw0NzIsNDY4LDQ2NSw0NjEsNDU5LDQ1Niw0NTUsNDUzLDQ1Miw0NTAsNDQ2LDQ0Miw0MzcsNDM0LDQzMiw0MzAsNDI5LDQyOCw0MzQsNDM3LDQzOSw0NDAsNDQyLDQ0Miw0NDIsNDQ0LDQ0Niw0NDYsNDQ2LDQ0Niw0NDUsNDQyLDQ0MSw0MzksNDM5LDQ0MCw0NDIsNDQzLDQ0NCw0NDQsNDQ0LDQ0NSw0NTAsNDUzLDQ1OCw0NjMsNDY3LDQ3MSw0NzIsNDcyLDQ3MSw0NzAsNDcwLDQ2OSw0NzAsNDcwLDQ3Miw0NzIsNDc0LDQ3NSw0NzcsNDc4LDQ3Nyw0NzQsNDcyLDQ3MCw0NzIsNDczLDQ3NSw0NzYsNDc1LDQ3NSw0NzYsNDczLDQ2OCw0NjQsNDU5LDQ1OSw0NTcsNDU2LDQ1NSw0NTYsNDU1LDQ1NSw0NTQsNDU0LDQ1Niw0NTYsNDU0LDQ1Niw0NTcsNDU5LDQ2Miw0NjQsNDY3LDQ2Nyw0NjksNDY2LDQ2NSw0NjMsNDU5LDQ2MSw0NTgsNDU2LDQ1Nyw0NTYsNDU3LDQ1NCw0NTYsNDU3LDQ1OSw0NjIsNDYxLDQ2Miw0NjQsNDYyLDQ2MSw0NjIsNDY1LDQ2OCw0NzAsNDcxLDQ3MSw0NzIsNDcwLDQ2OCw0NjksNDY4LDQ2Nyw0NjUsNDYzLDQ2Miw0NjEsNDYzLDQ2Myw0NjEsNDYxLDQ2MSw0NjIsNDYzLDQ2Nyw0NzAsNDcyLDQ3Myw0NzUsNDc2LDQ3Nyw0NzcsNDc1LDQ3Miw0NzAsNDY2LDQ2Myw0NjIsNDYyLDQ2NCw0NjYsNDY4LDQ2Nyw0NjcsNDY1LDQ2NCw0NjIsNDU5LDQ1OCw0NTksNDU5LDQ2MCw0NjEsNDYxLDQ2MCw0NTksNDU3LDQ1Niw0NTYsNDU5LDQ2NCw0NjksNDc1LDQ3OSw0ODIsNDg0LDQ4NSw0ODQsNDgzLDQ4MCw0NzUsNDc1LDQ3NCw0NzUsNDc4LDQ4Myw0ODcsNDg5LDQ4OSw0ODgsNDg0LDQ4Miw0ODAsNDgwLDQ4MCw0NzksNDc3LDQ3NSw0NzIsNDY3LDQ2Miw0NTgsNDUzLDQ1MCw0NDcsNDQ3LDQ0OCw0NTEsNDU1LDQ1Niw0NTYsNDU0LDQ1MSw0NDgsNDQyLDQ0MCw0MzYsNDMzLDQyOSw0MjYsNDI0LDQyNCw0MjYsNDI3LDQyOCw0MjksNDMwLDQzMCw0MjksNDI4LDQyNyw0MjcsNDI2LDQyNCw0MjUsNDI1LDQyNSw0MjUsNDI1LDQyNCw0MjQsNDIzLDQyMyw0MjIsNDIxLDQyMSw0MjEsNDIxLDQyMiw0MjMsNDI0LDQyNCw0MjQsNDIzLDQyMiw0MjEsNDIxLDQxOSw0MTYsNDEyLDQxMiw0MTQsNDIxLDQzNiw0NTgsNDk1LDU0NCw2MDYsNjc5LDc3Myw4NTcsOTE2LDk0NSw5NDUsOTE4LDg3NCw4MTQsNzMyLDY0NCw1NTIsNDY1LDM4OCwzMjgsMjg1LDI2MywyNjAsMjY4LDI4NSwzMDMsMzIyLDMzNiwzNDgsMzU5LDM2NywzNzMsMzc5LDM4NSwzODksMzkyLDM5MywzOTMsMzkzLDM5MiwzOTEsMzkyLDM5MiwzOTQsMzk3LDM5OSw0MDEsNDAwLDQwMiw0MDIsNDAxLDQwMCwzOTgsMzk3LDM5NiwzOTYsMzk2LDM5NSwzOTQsMzkzLDM5MywzOTIsMzkyLDM5MywzOTMsMzk0LDM5NCwzOTUsMzk1LDM5NiwzOTcsMzk5LDQwMiw0MDQsNDA4LDQwOSw0MTAsNDExLDQxMiw0MTQsNDE2LDQxNiw0MjIsNDI0LDQyNiw0MjcsNDI5LDQyOSw0MjksNDI3LDQyNSw0MjUsNDI3LDQyOSw0MzQsNDM4LDQ0MSw0NDMsNDQ0LDQ0Niw0NDgsNDQ5LDQ1Miw0NTQsNDU2LDQ1OCw0NTksNDYxLDQ2NCw0NjgsNDcxLDQ3NSw0NzksNDgyLDQ4Niw0OTAsNDk0LDQ5OCw1MDAsNTA0LDUwNiw1MDcsNTA4LDUwOSw1MTAsNTEyLDUxMyw1MTYsNTIwLDUyNiw1MzEsNTM2LDUzNyw1MzcsNTM4LDUzOCw1NDAsNTQyLDU0Niw1NTAsNTUzLDU1Niw1NTYsNTU3LDU2Miw1NjIsNTYzLDU2Miw1NjMsNTY2LDU2Myw1NjMsNTYxLDU1OCw1NTgsNTU4LDU1NSw1NTIsNTQ4LDU0NCw1NDAsNTM0LDUyOCw1MjQsNTE5LDUxNCw1MDksNTAzLDUwMCw0OTksNDk2LDQ5MCw0ODQsNDgwLDQ3NCw0NzEsNDY2LDQ2MSw0NjAsNDU4LDQ1NSw0NTMsNDUyLDQ0Nyw0NDcsNDQyLDQzOSw0MzcsNDM0LDQzMSw0MzMsNDM0LDQzNiw0MzcsNDM4LDQzNyw0MzcsNDM3LDQzOCw0MzUsNDM1LDQzMSw0MjksNDI1LDQyMiw0MjEsNDIxLDQyMiw0MjEsNDI0LDQyNCw0MjYsNDI1LDQyNSw0MjUsNDI0LDQyMyw0MjMsNDIzLDQyNCw0MjUsNDI3LDQzMCw0MzUsNDM4LDQ0MCw0NDAsNDM4LDQzNiw0MzMsNDMxLDQzMCw0MzEsNDMyLDQzNCw0MzUsNDM3LDQ0MCw0NDQsNDQ3LDQ0OSw0NTEsNDUwLDQ0OSw0NDcsNDQ2LDQ0NCw0NDQsNDQwLDQzOSw0MzgsNDM4LDQzNiw0MzcsNDM3LDQzNyw0MzcsNDM2LDQzNiw0MzUsNDMzLDQzMyw0MzIsNDMxLDQzMSw0MzMsNDM1LDQzOCw0MzksNDQyLDQ0NCw0NDUsNDQzLDQ0Nyw0NDgsNDQ4LDQ0Nyw0NDgsNDQ4LDQ1MSw0NTYsNDU5LDQ2NCw0NjcsNDY4LDQ2Nyw0NjUsNDYxLDQ1OCw0NTYsNDU0LDQ1Myw0NTIsNDUyLDQ1Miw0NTIsNDUyLDQ1MSw0NDksNDQ3LDQ0NSw0NDQsNDQ1LDQ0Niw0NDcsNDQ3LDQ0OCw0NDgsNDQ5LDQ0OCw0NDcsNDQ2LDQ0NSw0NDQsNDQ0LDQ0Niw0NDcsNDQ4LDQ0OCw0NTAsNDUwLDQ1MCw0NTAsNDUyLDQ1Niw0NTksNDYyLDQ2NSw0NjUsNDY2LDQ2NSw0NjQsNDYzLDQ2Miw0NjMsNDY0LDQ2Niw0NjgsNDY5LDQ2OSw0NjcsNDY1LDQ2Myw0NjIsNDYwLDQ1OSw0NTksNDYxLDQ2NSw0NjYsNDcwLDQ2OCw0NjYsNDYzLDQ2MCw0NTgsNDU4LDQ1OCw0NTgsNDU3LDQ1Nyw0NTcsNDU4LDQ1OCw0NTksNDYwLDQ2Miw0NjQsNDY3LDQ3Miw0NzcsNDgyLDQ4OCw0OTMsNDk3LDQ5OSw0OTksNDk3LDQ5Myw0OTAsNDkxLDQ5NCw0OTgsNTAyLDUwNSw1MDcsNTA2LDUwNyw1MDUsNTAwLDQ5Myw0ODksNDg2LDQ4Miw0ODAsNDc1LDQ3MSw0NjYsNDYzLDQ2MCw0NTksNDU4LDQ1OCw0NjAsNDYwLDQ1OSw0NTgsNDU2LDQ1Myw0NTAsNDQ2LDQ0Myw0NDIsNDQyLDQ0MSw0NDAsNDQyLDQ0NCw0NDUsNDQ0LDQ0Myw0NDIsNDQwLDQ0MCw0MzksNDQwLDQ0MCw0NDEsNDQzLDQ0NSw0NDcsNDQ1LDQ0NCw0NDIsNDQxLDQ0MCw0NDEsNDQxLDQ0Myw0NDgsNDQ4LDQ0OSw0NDksNDQ5LDQ0OSw0NDksNDUwLDQ1MCw0NDksNDQ0LDQ0NCw0NDIsNDM5LDQzNiw0MzYsNDM2LDQzNiw0MzYsNDM4LDQ0Miw0NDcsNDU4LDQ4MCw1MTIsNTU2LDYxMiw2ODMsNzcyLDg1Nyw5MjEsOTU3LDk2OCw5NDcsOTA5LDg1Myw3NzgsNjg1LDU5MCw1MDEsNDIzLDM2MSwzMTYsMjk3LDI5NSwzMDcsMzI0LDM0MywzNjEsMzc1LDM4NywzOTQsNDAwLDQwNCw0MDcsNDA5LDQxMCw0MDgsNDA4LDQwNyw0MDUsNDA3LDQwOCw0MTEsNDE0LDQxNyw0MTksNDIwLDQyNCw0MjIsNDIxLDQyMCw0MjEsNDIzLDQyMiw0MjQsNDI1LDQyNiw0MjcsNDI4LDQyOCw0MjgsNDI4LDQzMiw0MzQsNDM2LDQzNyw0NDAsNDQwLDQ0Miw0NDIsNDQ0LDQzOCw0NDAsNDM5LDQzNyw0MzYsNDM2LDQzNyw0NDAsNDQyLDQ0Niw0NDYsNDQ2LDQ0NSw0NDQsNDQ0LDQ0Myw0NDQsNDQ1LDQ0NSw0NDcsNDQ4LDQ1MCw0NTIsNDU0LDQ1Nyw0NjAsNDY1LDQ2Niw0NjgsNDcwLDQ3MSw0NzIsNDczLDQ3Niw0ODAsNDg1LDQ4OCw0OTEsNDkzLDQ5NSw0OTgsNTAwLDUwMyw1MDYsNTEwLDUxNSw1MjAsNTI0LDUyNyw1MzEsNTM0LDUzNiw1MzksNTQxLDU0NCw1NDYsNTQ2LDU0OCw1NTEsNTU0LDU1OCw1NjMsNTY3LDU3Miw1NzUsNTc4LDU4MSw1ODEsNTgyLDU4Miw1ODQsNTg1LDU4NCw1ODQsNTgyLDU4MSw1ODEsNTgxLDU4MCw1ODAsNTc5LDU3OCw1NzksNTc4LDU3Nyw1NzcsNTc2LDU3Myw1NzAsNTY1LDU1OCw1NTQsNTQ3LDU0MCw1MzQsNTI2LDUyMyw1MTgsNTEzLDUwOSw1MDQsNTAwLDQ5Nyw0OTMsNDg4LDQ4NCw0ODEsNDc3LDQ3NCw0NzEsNDY5LDQ2Niw0NjIsNDU5LDQ1Niw0NTMsNDUyLDQ1Miw0NTEsNDQ5LDQ0OCw0NDgsNDQ4LDQ0Nyw0NDcsNDQ1LDQ0Miw0NDEsNDQwLDQ0MCw0NDAsNDM5LDQzOSw0MzgsNDM4LDQzNiw0MzcsNDM4LDQ0MCw0NDQsNDQyLDQ0MSw0NDEsNDQxLDQ0Myw0NDQsNDQ1LDQ0Niw0NDYsNDQyLDQ0Niw0NDgsNDUwLDQ1MCw0NTEsNDUwLDQ0OSw0NDYsNDQ0LDQ0NSw0NDYsNDQ3LDQ0OCw0NDgsNDQ5LDQ1MCw0NTEsNDUyLDQ1NCw0NTYsNDU3LDQ1Niw0NTQsNDUyLDQ1MSw0NTAsNDQ5LDQ0Nyw0NDYsNDQ2LDQ0OCw0NTAsNDU0LDQ1NSw0NTgsNDU5LDQ1OCw0NTgsNDU3LDQ1Nyw0NTgsNDU2LDQ1Niw0NTYsNDU1LDQ1NSw0NTUsNDU1LDQ1Niw0NTgsNDU5LDQ2MCw0NjEsNDYxLDQ2Miw0NjIsNDYyLDQ2MSw0NjEsNDYwLDQ2MCw0NTksNDU5LDQ1OCw0NTYsNDU1LDQ1Niw0NTYsNDU5LDQ2MSw0NjMsNDY2LDQ2OSw0NzEsNDcyLDQ3NCw0NzQsNDc1LDQ3NCw0NzMsNDczLDQ3NCw0NzUsNDc0LDQ3NCw0NzQsNDc0LDQ3Myw0NzQsNDczLDQ3NCw0NzQsNDc0LDQ3NCw0NzUsNDc1LDQ3NSw0NzQsNDcyLDQ3MCw0NjcsNDY0LDQ2Miw0NTksNDYwLDQ2MCw0NTksNDYyLDQ2Myw0NjQsNDY0LDQ2Myw0NjYsNDY2LDQ2Niw0NjYsNDYzLDQ2MSw0NjEsNDYwLDQ1OSw0NTksNDU4LDQ1Nyw0NTgsNDU4LDQ1OCw0NTksNDYwLDQ2MCw0NTksNDU4LDQ1Nyw0NTYsNDU1LDQ1NSw0NTMsNDUxLDQ1MCw0NTAsNDUxLDQ1MCw0NDksNDQ4LDQ0Nyw0NDYsNDQzLDQ0Niw0NDgsNDQ4LDQ0OSw0NTEsNDUxLDQ1Miw0NTMsNDU2LDQ1Niw0NTYsNDU2LDQ1NSw0NTUsNDUxLDQ1Niw0NTYsNDU5LDQ1OSw0NTksNDU4LDQ1OSw0NTgsNDU2LDQ1Niw0NTYsNDU3LDQ1OCw0NTgsNDU5LDQ2MSw0NjQsNDY2LDQ2OCw0NjksNDY3LDQ2Nyw0NjUsNDYyLDQ2Miw0NjEsNDYzLDQ2Niw0NzAsNDc2LDQ3Nyw0ODAsNDgyLDQ4NCw0ODcsNDg4LDQ5MSw0OTMsNDk1LDQ5Niw0OTcsNDk2LDQ5NSw0OTQsNDk1LDQ5Niw0OTksNTAyLDUwNSw1MDcsNTA4LDUwNiw1MDUsNTAyLDQ5OCw0OTMsNDg5LDQ4NSw0ODIsNDc4LDQ3Miw0NjcsNDY0LDQ2Myw0NjQsNDY2LDQ2OCw0NjgsNDY4LDQ2OCw0NjQsNDY0LDQ2MSw0NjEsNDU5LDQ1OCw0NTYsNDU0LDQ1NCw0NTUsNDU1LDQ1NCw0NTUsNDU1LDQ1NCw0NTMsNDUxLDQ1MCw0NTAsNDQ5LDQ1MSw0NTIsNDUyLDQ1Miw0NTIsNDUwLDQ0OSw0NDksNDUwLDQ1Myw0NTQsNDU2LDQ1Niw0NTcsNDYwLDQ2Miw0NjMsNDY2LDQ2NSw0NjUsNDY0LDQ2Miw0NjAsNDU4LDQ1NSw0NTQsNDUzLDQ1Myw0NTQsNDU2LDQ1Nyw0NTgsNDYwLDQ2Myw0NjcsNDc0LDQ4OCw1MTQsNTUyLDYwMCw2NjMsNzQyLDgzNSw5MTAsOTYxLDk4Miw5NzgsOTUwLDkwMyw4NDEsNzYyLDY3Miw1ODUsNTA0LDQzMiwzNzgsMzQwLDMyMCwzMTksMzI3LDM0MSwzNTgsMzcyLDM4NSwzOTUsNDAyLDQwNiw0MTAsNDExLDQxMiw0MTMsNDEzLDQxNiw0MTAsNDA4LDQwNyw0MDgsNDEwLDQxMSw0MTMsNDE1LDQxNiw0MTcsNDE2LDQxNiw0MTcsNDE5LDQyMSw0MjQsNDI2LDQyNyw0MjksNDMxLDQzMyw0MzUsNDM3LDQzNiw0MzgsNDM4LDQzOCw0MzksNDM5LDQ0MCw0NDEsNDQxLDQ0MSw0NDIsNDQyLDQ0Miw0NDMsNDQyLDQ0Myw0NDMsNDQ0LDQ0Nyw0NDksNDUwLDQ1MCw0NTAsNDUwLDQ1MCw0NTEsNDUxLDQ1Myw0NTUsNDU3LDQ2MCw0NjIsNDY1LDQ2OCw0NzEsNDc0LDQ3Niw0ODAsNDgwLDQ4NCw0ODYsNDg4LDQ4OSw0OTEsNDkyLDQ5NCw0OTYsNDk3LDQ5Nyw0OTksNTAyLDUwNSw1MTAsNTE1LDUxOSw1MjMsNTI1LDUyNiw1MjcsNTI3LDUyOSw1MzEsNTM0LDUzNyw1NDIsNTQ3LDU1MSw1NTUsNTU4LDU2MSw1NjUsNTY4LDU3MSw1NzQsNTc4LDU4Myw1ODcsNTkxLDU5NCw1OTgsNjAwLDYwMSw2MDQsNjAzLDYwMyw2MDIsNjAyLDYwMiw2MDIsNjAxLDYwMCw2MDAsNTk4LDU5Niw1OTMsNTkwLDU4OCw1ODUsNTgyLDU4MCw1NzksNTc3LDU3NSw1NzEsNTcwLDU2Niw1NjIsNTU3LDU1Myw1NDksNTQ4LDU0NSw1NDIsNTM1LDUyOSw1MTksNTEyLDUwMyw0OTgsNDkyLDQ4OSw0ODUsNDgzLDQ4Miw0NzgsNDc1LDQ3Myw0NzMsNDc0LDQ3NCw0NzYsNDc2LDQ3NCw0NzIsNDY5LDQ2Nyw0NjQsNDYyLDQ2MSw0NjEsNDYwLDQ1OCw0NTcsNDU2LDQ1Myw0NTIsNDUyLDQ1Myw0NTMsNDU1LDQ1Niw0NTgsNDU4LDQ2Miw0NjEsNDYwLDQ1OCw0NTUsNDU5LDQ1OCw0NTgsNDY1LDQ2Niw0NjcsNDY1LDQ2Miw0NjYsNDY2LDQ2Niw0NjUsNDY0LDQ2NCw0NjYsNDcwLDQ3MSw0NzYsNDc2LDQ3Nyw0NzksNDgwLDQ3OSw0NzgsNDc4LDQ3OCw0NzcsNDc4LDQ4MCw0ODIsNDgzLDQ4Myw0ODMsNDgyLDQ4Miw0ODEsNDgxLDQ4MSw0ODIsNDgyLDQ4MSw0ODAsNDgwLDQ4MCw0ODAsNDgwLDQ3OCw0NzksNDgxLDQ4Miw0ODIsNDgzLDQ4Myw0ODQsNDg0LDQ4NCw0ODIsNDc5LDQ3Niw0NzUsNDc2LDQ3Niw0NzcsNDgwLDQ4Miw0ODIsNDgyLDQ4MSw0ODEsNDc5LDQ3OSw0NzgsNDc2LDQ3NSw0NzUsNDc2LDQ3OSw0ODMsNDg1LDQ4Nyw0ODcsNDg2LDQ4Nyw0ODcsNDg4LDQ4OCw0ODgsNDg5LDQ5MCw0OTMsNDk1LDQ5Niw0OTcsNDk2LDQ5Niw0OTgsNDk4LDQ5OCw0OTksNDk5LDUwMiw1MDIsNTAwLDQ5OCw0OTUsNDk0LDQ5Niw0OTgsNTAwLDQ5OCw0OTgsNDk1LDQ5Myw0OTMsNDkxLDQ5Myw0OTUsNTAwLDUwNCw1MDYsNTA4LDUwNyw1MDQsNTAwLDQ5NSw0OTAsNDg3LDQ4NSw0ODcsNDg5LDQ5MSw0OTIsNDkxLDQ5MCw0OTEsNDkyLDQ5Myw0OTIsNDkyLDQ5MSw0OTIsNDk0LDQ5Niw0OTksNTAwLDQ5OSw0OTgsNDk4LDQ5Nyw0OTcsNDk2LDQ5NSw0OTUsNDk2LDQ5OCw1MDEsNTA2LDUxMSw1MTQsNTE1LDUxNiw1MTQsNTEyLDUwOCw1MDYsNTAzLDUwMyw1MDIsNTA0LDUwMyw1MDUsNTA2LDUwNiw1MDgsNTEwLDUxNSw1MjAsNTI2LDUzMCw1MzIsNTM1LDUzNyw1MzcsNTM4LDUzNyw1MzYsNTM2LDUzNCw1MzIsNTMzLDUzNSw1MzksNTQ0LDU0Nyw1NTEsNTUyLDU1Myw1NTEsNTQ0LDUzNiw1MjYsNTIwLDUxNCw1MDgsNTA1LDUwMiw1MDMsNTA0LDUwNSw1MDUsNTA0LDUwNCw1MDAsNDk3LDQ5Niw0OTMsNDkxLDQ5Myw0OTIsNDg3LDQ4NCw0NzksNDc1LDQ3Miw0NzAsNDcwLDQ3MCw0NzIsNDcyLDQ3MSw0NzEsNDcwLDQ3MCw0NzEsNDcyLDQ3Myw0NzcsNDc3LDQ3Nyw0NzUsNDc0LDQ3Miw0NzAsNDY3LDQ2NSw0NjIsNDYyLDQ2NCw0NjcsNDcwLDQ3Miw0NzUsNDc3LDQ3Nyw0NzcsNDc2LDQ3Myw0NzMsNDczLDQ3Nyw0NzksNDgyLDQ4NCw0ODMsNDgwLDQ3Niw0NzYsNDc4LDQ4NCw0OTcsNTE5LDU1NSw2MDIsNjYzLDc0MCw4MzIsOTE0LDk3Miw5OTAsOTg4LDk2Nyw5MjcsODY4LDc5NCw2OTcsNjA1LDUxOSw0NDYsMzg4LDM0NywzMjQsMzE4LDMyNCwzMzgsMzU2LDM3NSwzOTIsNDA2LDQxNyw0MjUsNDMxLDQzMCw0MjgsNDI2LDQyOCw0MjcsNDI3LDQyNyw0MzAsNDMzLDQzNCw0MzYsNDM4LDQzOSw0MzksNDQxLDQ0Miw0NDQsNDQ2LDQ0Myw0NDUsNDQzLDQ0MSw0NDAsNDQxLDQ0NCw0NDUsNDQ2LDQ0OCw0NTAsNDUxLDQ1MCw0NTAsNDUxLDQ1Myw0NTUsNDU3LDQ1OSw0NTgsNDU3LDQ1Nyw0NTYsNDU3LDQ1OCw0NTksNDU3LDQ2Miw0NjEsNDYwLDQ1OSw0NjAsNDYxLDQ2MSw0NjEsNDYxLDQ2Myw0NjQsNDYzLDQ2Miw0NjEsNDYxLDQ2MSw0NjQsNDY2LDQ2OCw0NjksNDcwLDQ2OCw0NjYsNDYzLDQ2MSw0NjAsNDYzLDQ2Nyw0NzEsNDc1LDQ3Nyw0ODAsNDc5LDQ4MCw0ODEsNDgzLDQ4Niw0ODgsNDk0LDQ5OSw1MDMsNTA3LDUwOSw1MTIsNTE1LDUxOSw1MjEsNTIzLDUyNiw1MzIsNTMzLDUzOSw1NDcsNTU0LDU2MCw1NjYsNTcwLDU3Miw1NzUsNTc3LDU3OSw1ODIsNTg1LDU4OCw1ODksNTkwLDU4OSw1ODksNTkwLDU4OCw1OTIsNTkyLDU5NSw1OTYsNTk3LDU5OCw1OTcsNTk3LDU5Nyw1OTYsNTk0LDU5MSw1ODgsNTg2LDU4OCw1ODUsNTgzLDU4MCw1NzUsNTcxLDU2NCw1NTgsNTU0LDU0OSw1NDMsNTM2LDUzMCw1MjQsNTE5LDUxMyw1MDksNTAzLDUwMCw0OTUsNDkyLDQ4OSw0ODksNDg4LDQ4Nyw0ODYsNDgyLDQ3OSw0NzUsNDczLDQ3MSw0NzEsNDcwLDQ3MCw0NzAsNDY4LDQ2OCw0NjksNDcwLDQ3MSw0NzIsNDc0LDQ3Niw0NzYsNDc0LDQ3Myw0NzIsNDcxLDQ3MCw0NzAsNDcwLDQ3MSw0NzIsNDcyLDQ3NCw0NzcsNDgxLDQ4MSw0ODEsNDc4LDQ3Nyw0NzYsNDc4LDQ4MSw0ODMsNDg0LDQ4NCw0ODYsNDg4LDQ4OCw0ODksNDg5LDQ4OSw0ODksNDg4LDQ4Nyw0ODcsNDg3LDQ4Nyw0ODYsNDg2LDQ4OCw0OTAsNDkyLDQ5NCw0OTQsNDk1LDQ5NSw0OTUsNDk0LDQ5NCw0OTEsNDkwLDQ4OCw0ODgsNDkwLDQ5MCw0OTIsNDkzLDQ5Miw0OTEsNDkxLDQ5MSw0OTIsNDkzLDQ5Miw0OTIsNDkwLDQ5MSw0OTIsNDkyLDQ5Miw0OTQsNDk1LDQ5Nyw0OTcsNDk5LDQ5OSw1MDAsNTAwLDQ5OSw0OTksNDk5LDQ5OSw0OTksNTAwLDUwMiw1MDQsNTAyLDUwMCw0OTcsNDkzLDQ5MCw0ODksNDg3LDQ4Nyw0ODgsNDg5LDQ4OCw0ODcsNDg0LDQ4MCw0NzgsNDc1LDQ3NCw0NzQsNDc1LDQ3OCw0ODEsNDg0LDQ4NCw0ODQsNDgzLDQ4MSw0ODAsNDc4LDQ3NSw0NzgsNDc3LDQ3Niw0NzUsNDc0LDQ3Myw0NzIsNDcyLDQ3Myw0NzIsNDcyLDQ2OSw0NjgsNDY2LDQ2NSw0NjQsNDYzLDQ2NCw0NjUsNDY3LDQ2OSw0NzAsNDcxLDQ3MCw0NzAsNDY5LDQ2OCw0NzAsNDcyLDQ3NCw0NzMsNDcyLDQ3MSw0NzAsNDY5LDQ2Nyw0NjcsNDY3LDQ2Niw0NjUsNDY2LDQ2Nyw0NjcsNDcwLDQ3Miw0NzQsNDc2LDQ3OCw0NzksNDgwLDQ4Myw0ODYsNDg5LDQ5NSw0OTgsNTAyLDUwNyw1MTIsNTE1LDUxNyw1MjIsNTIzLDUyNCw1MjMsNTIyLDUyMSw1MjMsNTI1LDUzMCw1MzEsNTMxLDUzMiw1MzIsNTMwLDUzMCw1MjgsNTI0LDUyMSw1MjIsNTE4LDUxNSw1MTIsNTA2LDUwNCw1MDAsNDk4LDQ5Myw0OTMsNDk1LDQ5Niw0OTgsNDk3LDQ5Niw0OTQsNDkxLDQ4Nyw0ODYsNDg0LDQ4NSw0ODUsNDg1LDQ4NSw0ODgsNDg4LDQ4Nyw0ODYsNDg1LDQ4Nyw0ODYsNDg2LDQ4NCw0ODUsNDg0LDQ4Niw0ODUsNDg2LDQ4NSw0ODQsNDgzLDQ4MSw0NzksNDc3LDQ3Nyw0NzksNDc5LDQ4MCw0ODEsNDgzLDQ4NSw0ODcsNDg3LDQ4Nyw0ODcsNDg4LDQ5MCw0OTIsNDkyLDQ5Miw0OTEsNDkxLDQ5MCw0OTIsNDk0LDQ5Niw1MDIsNTEwLDUyNSw1NTMsNTkxLDY0OCw3MTYsODA3LDg5NCw5NjUsOTkwLDk5Miw5ODgsOTcyLDkyNiw4NjAsNzc0LDY3Miw1ODAsNDk2LDQyNSwzNzEsMzM4LDMyNSwzMjgsMzQyLDM1OSwzNzksMzk1LDQwOSw0MTgsNDIzLDQyNCw0MjIsNDIyLDQyMiw0MjAsNDE4LDQxNyw0MTgsNDE5LDQxOSw0MjAsNDIwLDQyMyw0MjQsNDI0LDQyNiw0MjcsNDI3LDQyNiw0MjUsNDI0LDQyMyw0MjIsNDIyLDQyMiw0MjAsNDIwLDQyMiw0MjMsNDI0LDQyNiw0MjUsNDIzLDQyMiw0MjEsNDIzLDQyMyw0MjUsNDI2LDQyNyw0MjgsNDI5LDQzMSw0MzMsNDM1LDQzNSw0MzgsNDM5LDQzOCw0MzcsNDM3LDQzNyw0MzcsNDM4LDQ0MCw0NDMsNDQ3LDQ1MCw0NTMsNDU2LDQ1Niw0NTgsNDU4LDQ2MCw0NjEsNDYzLDQ2Miw0NjMsNDY1LDQ2Nyw0NzAsNDcyLDQ3Niw0NzgsNDgxLDQ4NCw0ODYsNDg5LDQ5Miw0OTcsNTAwLDUwMiw1MDYsNTA4LDUxMSw1MTQsNTE4LDUyMiw1MjgsNTM0LDUzOCw1NDEsNTQ0LDU0Niw1NDgsNTUwLDU1Niw1NTYsNTYwLDU2Myw1NjcsNTY5LDU3Miw1NzUsNTc4LDU4MSw1ODQsNTg3LDU4OCw1ODYsNTg2LDU4Niw1ODcsNTg3LDU4OSw1ODksNTg5LDU4OSw1ODcsNTg0LDU4Myw1ODAsNTc3LDU3NCw1NzMsNTcxLDU3MCw1NjgsNTY0LDU2MCw1NTcsNTUzLDU1MCw1NDYsNTQxLDUzNSw1MjgsNTIxLDUxNiw1MTIsNTA4LDUwNCw1MDAsNDk2LDQ5MSw0ODUsNDgzLDQ4MCw0NzcsNDc0LDQ3MCw0NjQsNDYwLDQ1Myw0NDgsNDQ0LDQ0Miw0NDAsNDM3LDQzOCw0MzgsNDM3LDQzNSw0MzYsNDM2LDQzNCw0MzMsNDMyLDQzMiw0MzEsNDI5LDQyOCw0MjcsNDI3LDQyNyw0MjcsNDI2LDQyNCw0MjQsNDI0LDQyNCw0MjYsNDI1LDQyNiw0MjYsNDI2LDQyNyw0MjgsNDI3LDQyNyw0MjcsNDI3LDQyOCw0MjksNDMwLDQzMCw0MjksNDMxLDQzMyw0MzYsNDM4LDQ0MSw0NDQsNDQ3LDQ1MCw0NTEsNDUxLDQ1MCw0NTEsNDUxLDQ1MSw0NTEsNDUyLDQ1Miw0NTMsNDU1LDQ1Myw0NTIsNDUwLDQ0OCw0NDcsNDQ1LDQ0NCw0NDIsNDQyLDQzOSw0MzcsNDM3LDQ0MCw0NDAsNDQxLDQ0NCw0NDMsNDQzLDQ0Miw0NDAsNDM5LDQzOCw0MzcsNDM3LDQzOCw0MzcsNDM2LDQzNyw0MzgsNDM3LDQzNyw0MzUsNDM0LDQzNCw0MzMsNDMyLDQzMiw0MzAsNDMwLDQzMiw0MzEsNDMxLDQzMSw0MzEsNDMxLDQzMiw0MzAsNDI3LDQzMCw0MzAsNDMwLDQzMyw0MzQsNDM2LDQzNyw0MzcsNDM5LDQ0MCw0MzgsNDM4LDQzNyw0MzUsNDM0LDQzNCw0MzUsNDM3LDQzOSw0NDAsNDQxLDQ0MSw0NDEsNDQwLDQ0MCw0NDAsNDM5LDQ0MCw0NDAsNDQxLDQ0MSw0NDMsNDQ0LDQ0Niw0NDYsNDQ3LDQ0Nyw0NDksNDUyLDQ1NSw0NTcsNDU4LDQ1Nyw0NTcsNDU4LDQ1OSw0NjIsNDYxLDQ2Miw0NjIsNDYwLDQ2MCw0NTksNDU5LDQ2MCw0NjEsNDYzLDQ2NCw0NjQsNDYzLDQ2MSw0NTksNDU4LDQ1Nyw0NTcsNDU5LDQ2MCw0NjAsNDYxLDQ2MSw0NjEsNDYyLDQ2Myw0NjQsNDY2LDQ2OSw0NzEsNDc0LDQ3NSw0NzUsNDgwLDQ3NSw0NzQsNDcyLDQ3MCw0NzAsNDcwLDQ3MSw0NzQsNDc1LDQ3Nyw0ODEsNDg2LDQ5MSw0OTcsNTAyLDUwNSw1MDgsNTEyLDUxMiw1MTIsNTEyLDUxMCw1MDgsNTA4LDUxMiw1MTUsNTE5LDUyMSw1MjMsNTIzLDUyMSw1MjAsNTE4LDUxNSw1MTUsNTE1LDUxNiw1MTUsNTEyLDUwOCw1MDQsNTAwLDQ5Niw0OTIsNDkwLDQ4OCw0ODYsNDg1LDQ4NCw0ODMsNDgxLDQ3Nyw0NzQsNDcwLDQ2Niw0NjIsNDYwLDQ1OCw0NTYsNDU3LDQ1OCw0NTksNDYwLDQ1OSw0NTgsNDU1LDQ1Myw0NTEsNDUwLDQ0OSw0NDksNDQ5LDQ0OCw0NDksNDQ3LDQ0Nyw0NDcsNDQ2LDQ0Nyw0NDYsNDQ1LDQ0NCw0NDIsNDQxLDQ0MCw0NDEsNDQyLDQ0NCw0NDUsNDQ1LDQ0NSw0NDQsNDQ1LDQ0Myw0NDQsNDQzLDQ0Niw0NDUsNDQ0LDQ0Myw0NDQsNDQ5LDQ1Niw0NzEsNDk4LDUzOCw1ODgsNjUzLDczMSw4MjIsODk3LDk0Nyw5NjgsOTYyLDkzMCw4ODQsODE4LDczNCw2NDUsNTU1LDQ3Miw0MDEsMzQ2LDMxMCwyOTYsMjk3LDMwOSwzMjgsMzQ4LDM2NiwzODEsMzkyLDQwMSw0MDQsNDA2LDQwOCw0MDksNDA4LDQwOSw0MDksNDEwLDQxMCw0MTIsNDEzLDQxNSw0MTQsNDEzLDQxMyw0MTQsNDE1LDQxNiw0MTcsNDE4LDQyMCw0MjAsNDIxLDQyMCw0MTksNDE5LDQyMCw0MjAsNDIxLDQyMSw0MTksNDIzLDQyNCw0MjUsNDI0LDQyNCw0MjUsNDI2LDQyOCw0MzIsNDM0LDQzNyw0NDAsNDQxLDQ0Myw0NDUsNDQ1LDQ0NSw0NDQsNDQ0LDQ0Miw0NDIsNDQ0LDQ0NSw0NDYsNDQ4LDQ0OSw0NTAsNDUwLDQ1Miw0NTUsNDU1LDQ1Niw0NjIsNDYyLDQ2NCw0NjcsNDY3LDQ3MCw0NzAsNDcwLDQ3MCw0NzEsNDcyLDQ3NSw0NzgsNDgwLDQ4Miw0ODgsNDg4LDQ5Miw0OTUsNDk4LDUwMCw1MDMsNTA2LDUwOSw1MTQsNTE4LDUyNCw1MzAsNTM0LDUzOSw1MzgsNTM5LDU0MCw1NDMsNTQ2LDU1MCw1NTMsNTU0LDU1Niw1NTUsNTYyLDU2Miw1NjQsNTY1LDU2NCw1NjgsNTY3LDU2OCw1NjksNTcwLDU3Miw1NzEsNTcyLDU3Miw1NzQsNTc1LDU3Nyw1NzksNTgwLDU4MCw1ODQsNTgxLDU4MCw1NzIsNTY0LDU1OCw1NDgsNTQxLDUzNSw1MzAsNTIzLDUxOCw1MTMsNTA4LDUwMyw0OTksNDkyLDQ4Niw0ODAsNDcxLDQ2NCw0NTcsNDUwLDQ0Myw0MzYsNDMwLDQyNiw0MjEsNDE2LDQxNCw0MTIsNDEwLDQwMyw0MDMsMzk3LDM5MCwzODIsMzc3LDM3MCwzNjQsMzU4LDM1MywzNDksMzQ1LDM0MywzNDIsMzQyLDMzOCwzNDAsMzM4LDMzNCwzMzAsMzI2LDMyMywzMjEsMzIxLDMyMCwzMjAsMzIwLDMyMSwzMjIsMzIxLDMyMiwzMjEsMzIxLDMyMSwzMjMsMzI0LDMyNCwzMjUsMzI1LDMyNiwzMjgsMzMwLDMzMiwzMzIsMzMxLDMzMiwzMzEsMzMwLDMzMCwzMzAsMzMxLDMzMCwzMzAsMzMwLDMyOCwzMjgsMzI3LDMyNywzMjgsMzI3LDMyOCwzMjksMzMwLDMzMSwzMzIsMzM1LDMzNSwzMzUsMzM0LDMzNCwzMzIsMzMyLDMzMiwzMzEsMzMzLDMzNCwzMzcsMzQwLDM0MCwzNDEsMzM5LDMzOCwzMzYsMzM1LDMzNCwzMzMsMzMzLDMzNCwzMzUsMzM4LDM0MCwzNDMsMzQ0LDM0NSwzNDYsMzQ1LDM0NywzNDksMzUxLDM1MSwzNTAsMzQ5LDM0NiwzNDUsMzQ0LDM0NCwzNDQsMzQ2LDM0NiwzNDcsMzQ3LDM0NiwzNDgsMzQ5LDM1MSwzNTIsMzU0LDM1NSwzNTksMzYxLDM2MSwzNjMsMzYyLDM2NCwzNjUsMzY1LDM2NiwzNjUsMzY2LDM2NiwzNjUsMzY1LDM2NywzNzAsMzcyLDM3NiwzODEsMzgzLDM4OCwzODgsMzg5LDM5MCwzOTEsMzkyLDM5NCwzOTYsMzk4LDQwMCw0MDIsNDAzLDQwMyw0MDQsNDA2LDQwNyw0MDcsNDA4LDQwOSw0MDgsNDA3LDQwNSw0MDYsNDA1LDQwNSw0MDYsNDA2LDQwNiw0MDgsNDEwLDQxNCw0MTcsNDIxLDQyNCw0MjUsNDI3LDQyOCw0MjgsNDI4LDQyOCw0MjgsNDI3LDQyNiw0MjcsNDI4LDQyOSw0MzAsNDI5LDQyOSw0MzAsNDMyLDQzMiw0MzMsNDM1LDQzNyw0MzksNDQzLDQ0Nyw0NTMsNDU3LDQ2Myw0NjgsNDczLDQ3Niw0ODAsNDgyLDQ4Miw0ODIsNDgzLDQ4Niw0OTAsNDk0LDQ5NSw0OTcsNTAwLDUwMSw1MDIsNTA0LDUwMyw1MDEsNDk5LDQ5NSw0OTUsNDkxLDQ4NSw0NzksNDc0LDQ3MSw0NjgsNDY3LDQ2Nyw0NjgsNDcwLDQ3MSw0NzEsNDc1LDQ3Nyw0NzksNDc3LDQ3NCw0NzAsNDY2LDQ2Myw0NjAsNDYwLDQ1OSw0NjAsNDYxLDQ2MSw0NjAsNDYwLDQ2Miw0NjMsNDY2LDQ2OCw0NzAsNDcxLDQ3Myw0NzUsNDc2LDQ3NSw0NzUsNDc1LDQ3Nyw0NzksNDgwLDQ4MSw0ODEsNDgyLDQ4Myw0ODUsNDg3LDQ4OCw0OTMsNDk4LDUwMiw1MDcsNTEwLDUxMiw1MTIsNTEwLDUwOSw1MDgsNTA2LDUwOCw1MDYsNTA3LDUxMiw1MTYsNTI3LDU1MCw1ODUsNjMxLDY5MCw3NjgsODU2LDkzNiw5OTAsOTkzLDk5NCw5OTAsOTcxLDkyNiw4NTcsNzcyLDY3NSw1OTAsNTE0LDQ0OSw0MDMsMzc0LDM2NCwzNjcsMzc3LDM5Miw0MDYsNDIwLDQzMSw0MzksNDQ1LDQ0Nyw0NDksNDQ4LDQ0NSw0NDUsNDQ2LDQ0OCw0NTAsNDUzLDQ1NSw0NTYsNDU4LDQ1OSw0NjAsNDU5LDQ1Nyw0NTUsNDU2LDQ1Miw0NTIsNDUyLDQ1Miw0NTMsNDUzLDQ1Myw0NTQsNDU1LDQ1NSw0NTQsNDQ5LDQ1MSw0NTEsNDUzLDQ1NSw0NjAsNDYzLDQ2Niw0NjcsNDY4LDQ2NSw0NjcsNDY2LDQ2Myw0NjEsNDYwLDQ1OSw0NTksNDYwLDQ2MSw0NjMsNDY1LDQ2Nyw0NzEsNDc0LDQ3NCw0NzgsNDgwLDQ4MSw0ODMsNDgzLDQ4Nyw0ODcsNDg5LDQ5Miw0OTIsNDkzLDQ5Miw0OTQsNDk0LDQ5NCw0OTQsNDk3LDQ5OSw1MDIsNTA2LDUwOCw1MTIsNTEzLDUxNSw1MTcsNTIwLDUyMiw1MjQsNTI3LDUyOSw1MzEsNTMyLDUzNCw1MzgsNTQyLDU0Nyw1NTEsNTU2LDU1Nyw1NTksNTU5LDU2MCw1NjMsNTY2LDU3Miw1NzYsNTc4LDU4MCw1ODIsNTgxLDU4NCw1ODUsNTg1LDU4Niw1ODYsNTg3LDU4OSw1OTEsNTkzLDU5Nyw1OTksNjAyLDYwMiw2MDIsNjAxLDU5OSw1OTQsNTkwLDU4NSw1ODAsNTc5LDU3NSw1NzMsNTczLDU3Miw1NzAsNTY4LDU2NCw1NTgsNTUyLDU0OCw1NDMsNTQwLDUzNiw1MzIsNTI3LDUyNCw1MjIsNTE5LDUxOCw1MTUsNTEyLDUwOCw1MDEsNDk1LDQ4OCw0ODMsNDc4LDQ3Niw0NzQsNDc0LDQ3NCw0NzQsNDc2LDQ3Niw0NzcsNDc3LDQ3OCw0NzYsNDc0LDQ3MCw0NjgsNDY2LDQ2NSw0NjYsNDY2LDQ2Niw0NjYsNDY1LDQ2NSw0NjIsNDYxLDQ1OCw0NTYsNDU1LDQ1NSw0NTcsNDYxLDQ2NCw0NjcsNDY2LDQ2Niw0NjMsNDYxLDQ1Nyw0NTUsNDU0LDQ1NSw0NTgsNDU5LDQ2Miw0NjYsNDY5LDQ3MCw0NzEsNDc0LDQ3Niw0ODAsNDgzLDQ4Niw0ODksNDkwLDQ5Miw0OTIsNDkzLDQ5NSw0OTYsNDk2LDQ5NSw0OTMsNDkyLDQ5MSw0OTAsNDkwLDQ5MSw0OTMsNDkzLDQ5NCw0OTYsNDk4LDQ5OSw1MDAsNTAxLDUwMiw0OTksNDk4LDQ5OCw0OTksNTA0LDUwNyw1MDgsNTA5LDUxMCw1MDgsNTA3LDUwNiw1MDYsNTA2LDUwNiw1MDcsNTA5LDUxMiw1MTYsNTE5LDUyMCw1MTksNTE4LDUxOCw1MTcsNTE1LDUxNCw1MTIsNTA5LDUxMiw1MDgsNTEyLDUxMyw1MTQsNTE2LDUxOCw1MTksNTE4LDUxNSw1MTgsNTE2LDUxNSw1MTIsNTEyLDUxMiw1MTQsNTE2LDUxOCw1MTgsNTIyLDUyMSw1MjIsNTIzLDUyMyw1MjcsNTMwLDUzMiw1MzYsNTM4LDU0MCw1NDAsNTQxLDU0Miw1NDAsNTM5LDUzOCw1MzcsNTM0LDUzNCw1MzYsNTM4LDU0MSw1NDIsNTQ1LDU0Nyw1NDgsNTQ5LDU1MCw1NTAsNTUyLDU0Niw1NDMsNTQxLDU0MCw1NDAsNTQxLDU0NCw1NDUsNTQ5LDU1Miw1NTQsNTU1LDU1Niw1NTUsNTU2LDU1Nyw1NTksNTY0LDU2NSw1NzEsNTc2LDU4Miw1ODgsNTg3LDU4OCw1ODYsNTg2LDU4NSw1ODQsNTg0LDU4Niw1ODgsNTkxLDU5Niw1OTksNjAwLDU5OSw1OTksNTk3LDU5NCw1OTAsNTg1LDU4MCw1NzcsNTc1LDU3Myw1NzAsNTY4LDU2OCw1NjgsNTY2LDU2Myw1NjAsNTU2LDU1NCw1NTIsNTUwLDU0Niw1NDIsNTQwLDUzOSw1MzksNTM3LDUzNCw1MzAsNTI3LDUyNiw1MjYsNTI5LDUzMSw1MzQsNTM0LDUzMiw1MzAsNTMwLDUzMCw1MzAsNTMxLDUzMSw1MzIsNTMxLDUyOSw1MjYsNTIxLDUxOCw1MTUsNTE0LDUxNiw1MTcsNTIwLDUyMCw1MTksNTE3LDUxNSw1MTMsNTEwLDUwOCw1MDcsNTA3LDUwNyw1MDcsNTA3LDUwOSw1MTAsNTExLDUxMSw1MTAsNTA5LDUxMSw1MTUsNTIzLDUzNyw1NjEsNTk3LDY0NCw3MDQsNzg0LDg3Myw5NTUsOTkxLDk5Myw5OTIsOTkxLDk4Myw5NDQsODc2LDc4Niw2ODEsNTg3LDUwNSw0MzgsMzkwLDM2MSwzNTMsMzU4LDM3MiwzOTEsNDEwLDQyNyw0NDEsNDUyLDQ1OCw0NjQsNDY1LDQ2Niw0NjYsNDY1LDQ2NCw0NjUsNDY3LDQ2OCw0NjcsNDY4LDQ2OCw0NzAsNDcwLDQ3MSw0NzEsNDcwLDQ3MSw0NzAsNDcwLDQ2Nyw0NjUsNDYzLDQ2MSw0NjAsNDYwLDQ2MSw0NjMsNDY1LDQ2Nyw0NjksNDcxLDQ3Myw0NzUsNDc3LDQ3OSw0ODAsNDgwLDQ3OSw0NzcsNDczLDQ3MCw0NjksNDY5LDQ3MSw0NzMsNDc1LDQ3Niw0NzUsNDc1LDQ3NCw0NzUsNDc1LDQ3Niw0NzcsNDc3LDQ3Nyw0NzksNDgyLDQ4NCw0ODcsNDg5LDQ5MCw0OTEsNDkwLDQ4OSw0ODgsNDg3LDQ5MCw0OTIsNDk0LDQ5Myw0OTQsNDk1LDQ5Niw0OTgsNTAwLDQ5OSw1MDQsNTA3LDUxMiw1MTUsNTE4LDUyMCw1MjIsNTIxLDUyMSw1MjEsNTIzLDUyNiw1MjksNTMyLDUzNCw1MzUsNTM3LDUzOSw1NDEsNTQ2LDU0OSw1NTEsNTUyLDU1Miw1NTEsNTUyLDU1NCw1NTcsNTYwLDU2Miw1NjUsNTY3LDU2Nyw1NjcsNTY3LDU2Niw1NjcsNTY5LDU3MCw1NzIsNTcxLDU3MCw1NjYsNTYzLDU2MSw1NjAsNTU4LDU1NSw1NDksNTQ4LDU0Myw1MzgsNTMzLDUyOSw1MjIsNTE2LDUxMiw1MDYsNTAxLDQ5NSw0ODksNDgzLDQ3Nyw0NjksNDY5LDQ2NSw0NjIsNDU5LDQ1Nyw0NTMsNDQ5LDQ0NCw0NDEsNDM5LDQzNSw0MzIsNDMwLDQyNiw0MjIsNDIxLDQxOCw0MTYsNDE1LDQxMyw0MTAsNDA4LDQwOCw0MDUsNDA1LDQwNSw0MDUsNDA2LDQwNiw0MDUsNDA3LDQwNyw0MDgsNDA5LDQxMCw0MDksNDEwLDQxMSw0MTQsNDE2LDQxOCw0MjAsNDE4LDQxNyw0MTIsNDEwLDQwOSw0MTEsNDEzLDQxNSw0MTcsNDIwLDQyMiw0MjMsNDIzLDQyNCw0MjQsNDI2LDQyNyw0MzAsNDMwLDQzMCw0MjcsNDI3LDQyNCw0MjAsNDIwLDQxOCw0MjAsNDIwLDQxOSw0MTksNDIwLDQxOCw0MTgsNDIwLDQyMCw0MjIsNDI0LDQyNyw0MjgsNDMxLDQzNCw0MzQsNDM0LDQzNCw0MzMsNDMwLDQyNyw0MjUsNDI0LDQyMyw0MjYsNDI0LDQyOCw0MjUsNDI1LDQyNiw0MjYsNDI4LDQyNyw0MjgsNDI5LDQyOSw0MzEsNDMzLDQzNCw0MzUsNDM2LDQzNyw0MzgsNDM4LDQzOCw0MzgsNDM4LDQzOSw0NDEsNDQzLDQ0Niw0NDksNDUyLDQ1NCw0NTUsNDU0LDQ1MCw0NTIsNDUxLDQ1Miw0NTMsNDU2LDQ1OCw0NjAsNDYzLDQ2NSw0NjUsNDY1LDQ2NSw0NjYsNDY4LDQ2OSw0NzAsNDcyLDQ3Miw0NzIsNDY5LDQ3MCw0NjksNDY3LDQ2Niw0NjQsNDYxLDQ1OSw0NTgsNDU3LDQ1Niw0NTQsNDU0LDQ1Myw0NTIsNDUwLDQ1MCw0NTEsNDUzLDQ1NCw0NTUsNDU2LDQ1Niw0NTUsNDUyLDQ1MCw0NDYsNDQxLDQzNyw0MzQsNDMyLDQzMSw0MzIsNDMzLDQzNiw0NDEsNDQ0LDQ1MCw0NTQsNDU3LDQ2MCw0NjIsNDYzLDQ2NSw0NjYsNDY2LDQ2Niw0NjQsNDYzLDQ2Myw0NjQsNDY0LDQ2NCw0NjMsNDYzLDQ2Miw0NTgsNDU1LDQ1NCw0NDksNDQ3LDQ0NSw0NDMsNDQwLDQzNiw0MzMsNDI3LDQyNCw0MjEsNDE5LDQxNyw0MTQsNDE0LDQxMSw0MTAsNDEwLDQxMCw0MTEsNDEyLDQxMiw0MTEsNDEyLDQxMSw0MTMsNDE0LDQxNSw0MTYsNDE2LDQxOCw0MjAsNDIxLDQyMCw0MTcsNDEzLDQxMiw0MTIsNDE0LDQxOCw0MjIsNDI0LDQyNiw0MjYsNDI3LDQyNiw0MjcsNDI4LDQyOSw0MjksNDI4LDQyOCw0MjksNDI5LDQzMiw0MzQsNDM3LDQ0MCw0MzksNDQzLDQ0NSw0NDcsNDQ5LDQ1Miw0NTQsNDU3LDQ1OSw0NjQsNDcxLDQ4MCw0OTQsNTE4LDU1NSw2MDIsNjYxLDczNiw4MjgsOTA4LDk2NCw5ODcsOTg2LDk2MSw5MTYsODU4LDc4MSw2ODYsNTk2LDUxMiw0MzUsMzc1LDMzOSwzMjQsMzI0LDMzOCwzNTUsMzczLDM4OCwzOTksNDA4LDQxNCw0MjAsNDI0LDQyNiw0MjYsNDI0LDQyNCw0MjEsNDE5LDQxOSw0MTgsNDIwLDQyMSw0MjIsNDIzLDQyNSw0MjcsNDI5LDQzMSw0MzIsNDMwLDQyOSw0MjUsNDIwLDQxNSw0MDgsNDA0LDQwMCwzOTYsMzk0LDM5MCwzOTAsMzg4LDM4NiwzODIsMzc2LDM3MiwzNjgsMzY2LDM2NSwzNjMsMzY1LDM2NiwzNjksMzcyLDM3NiwzNzksMzg1LDM4OSwzOTQsNDAwLDQwNCw0MDksNDEwLDQxMyw0MTQsNDE4LDQyMCw0MjMsNDI1LDQyOCw0MzAsNDMyLDQzNiw0NDAsNDQzLDQ0Nyw0NTEsNDU1LDQ1OCw0NjAsNDY1LDQ2OSw0NzMsNDc4LDQ4MSw0ODQsNDg2LDQ4OCw0ODksNDg3LDQ4OSw0OTIsNDk2LDQ5OSw1MDMsNTA4LDUxMyw1MTcsNTIxLDUyOCw1MzMsNTM5LDU0NCw1NDgsNTUxLDU1Myw1NTUsNTU4LDU2Miw1NjcsNTcxLDU3Niw1ODAsNTgyLDU4NSw1ODUsNTg2LDU4Niw1ODUsNTgzLDU4Niw1ODQsNTg2LDU4Myw1ODYsNTg3LDU5MCw1OTQsNTk1LDU5NSw1OTUsNTk0LDU5Miw1ODgsNTg3LDU4NSw1ODMsNTg0LDU4MCw1ODAsNTczLDU2OCw1NjMsNTU4LDU1NCw1NTAsNTQ2LDU0MSw1MzUsNTI4LDUyMiw1MTgsNTE1LDUxMiw1MDksNTA1LDUwMSw0OTYsNDkyLDQ4OSw0ODYsNDg0LDQ4Myw0ODIsNDgxLDQ3OSw0NzcsNDc2LDQ3NSw0NzMsNDcwLDQ2OCw0NjcsNDY1LDQ2NCw0NjMsNDYzLDQ2NCw0NjQsNDY0LDQ2NSw0NjYsNDY2LDQ2OSw0NjksNDY3LDQ2NCw0NjAsNDU3LDQ1NCw0NTEsNDQ4LDQ0Nyw0NDYsNDQ1LDQ0NCw0NDQsNDQ0LDQ0NSw0NDcsNDQ5LDQ1MSw0NTEsNDU2LDQ1OCw0NjAsNDYwLDQ2MCw0NjAsNDYwLDQ2MSw0NjIsNDY1LDQ2OSw0NzIsNDc3LDQ4MCw0ODMsNDg0LDQ4NCw0ODMsNDgwLDQ4MSw0ODAsNDc4LDQ3Niw0NzMsNDcxLDQ2OSw0NjcsNDY2LDQ2Nyw0NjgsNDcwLDQ3MCw0NzEsNDY5LDQ2Nyw0NjYsNDY1LDQ2NCw0NjQsNDY0LDQ2NSw0NjYsNDY2LDQ2NSw0NjUsNDY1LDQ2Myw0NjEsNDU3LDQ1NSw0NTIsNDUwLDQ1Miw0NDgsNDQ4LDQ0Niw0NDQsNDQ0LDQ0Miw0NDEsNDM5LDQzOCw0MzgsNDM2LDQ0MCw0NDIsNDQyLDQ0Miw0NDMsNDQzLDQ0Miw0NDIsNDQxLDQ0MSw0NDIsNDQzLDQ0Myw0NDMsNDQ0LDQ0NCw0NDMsNDQwLDQzNyw0MzQsNDM0LDQzMyw0MzMsNDM1LDQzNyw0MzgsNDM5LDQ0MSw0NDIsNDQzLDQ0NCw0NDYsNDQ4LDQ1MSw0NTQsNDU4LDQ2MSw0NjQsNDY1LDQ2NSw0NjQsNDYzLDQ2Myw0NjQsNDY0LDQ2Niw0NjcsNDY3LDQ2Nyw0NjcsNDY2LDQ2NSw0NjUsNDY2LDQ2Niw0NjgsNDY3LDQ2Nyw0NjYsNDY2LDQ2NSw0NjQsNDYzLDQ2Niw0NjYsNDY3LDQ2Nyw0NjcsNDY3LDQ2Nyw0NjgsNDcwLDQ3Miw0NzMsNDcyLDQ3Miw0NjksNDY1LDQ2MSw0NTYsNDU1LDQ1NCw0NTMsNDU0LDQ1NCw0NTQsNDU0LDQ1Niw0NTksNDYyLDQ2NSw0NzIsNDcyLDQ3Niw0ODAsNDgzLDQ4Niw0ODYsNDg2LDQ4Nyw0ODcsNDg4LDQ4Nyw0ODcsNDg4LDQ4Nyw0ODQsNDgyLDQ3OSw0NzgsNDc1LDQ3NCw0NzEsNDY2LDQ1OSw0NTMsNDQ3LDQ0MSw0MzUsNDI5LDQyNSw0MjIsNDE5LDQxNyw0MTYsNDE1LDQxNSw0MTYsNDE2LDQxNiw0MTcsNDE4LDQxNyw0MTYsNDEzLDQxMCw0MDcsNDA1LDQwNCw0MDIsNDAyLDQwMSw0MDAsMzk4LDM5NywzOTcsMzk4LDM5OCwzOTcsNDAxLDQwMSw0MDIsNDAyLDQwMyw0MDUsNDA1LDQwNyw0MTAsNDEyLDQxNSw0MTcsNDIwLDQyNCw0MjIsNDI2LDQyNiw0MjUsNDIzLDQyMSw0MjMsNDIyLDQyNSw0MjcsNDMxLDQyOSw0MzMsNDM1LDQzNSw0MzUsNDMzLDQzOCw0NDMsNDQ5LDQ1OCw0NzYsNDk5LDUzOCw1ODUsNjQ0LDcxNCw4MDYsODc5LDkyNiw5NDUsOTM5LDkwOSw4NjQsODAwLDcxOCw2MzMsNTQ5LDQ3MCw0MDIsMzQ4LDMxMSwyOTMsMjkwLDI5OCwzMDksMzI1LDM0MCwzNTQsMzYzLDM3MiwzNzgsMzgyLDM4NiwzODksMzg5LDM5MSwzOTEsMzkwLDM5MCwzODksMzg5LDM5MCwzOTEsMzkyLDM5MSwzOTEsMzg5LDM5MSwzODksMzg5LDM5MCwzOTAsMzkxLDM5NCwzOTYsMzk5LDQwMiw0MDQsNDA1LDQwNSw0MDYsNDA1LDQwOCw0MDcsNDA3LDQwOCw0MDcsNDA1LDQwNCw0MDMsNDAzLDQwNSw0MDcsNDA5LDQxMSw0MTIsNDEzLDQxNSw0MTcsNDIwLDQyMyw0MjQsNDIzLDQyMiw0MjEsNDIwLDQxOCw0MTcsNDE3LDQxOCw0MTcsNDE4LDQxOCw0MTksNDE4LDQxNyw0MTgsNDE4LDQxOSw0MTksNDIwLDQxOSw0MjAsNDIxLDQyMiw0MjQsNDI3LDQzMSw0MzUsNDM4LDQ0MCw0NDEsNDQyLDQ0Miw0NDQsNDQ3LDQ1MCw0NTQsNDU4LDQ2Miw0NjYsNDcxLDQ3Niw0ODAsNDg0LDQ4NSw0ODgsNDkwLDQ5Myw0OTUsNDk4LDUwMiw1MDYsNTA2LDUwNiw1MDcsNTA3LDUxMCw1MTIsNTEyLDUxMyw1MTQsNTE0LDUxNSw1MTcsNTE5LDUxOSw1MTgsNTE4LDUxNiw1MTQsNTEzLDUxMyw1MTIsNTEzLDUxMiw1MDksNTA2LDUwMSw0OTcsNDkxLDQ5Miw0OTAsNDg3LDQ4Myw0NzgsNDcxLDQ2NSw0NTksNDU0LDQ0NSw0NDAsNDM0LDQyOSw0MjQsNDIxLDQxNiw0MTEsNDA1LDQwMiwzOTcsMzkzLDM5MCwzODYsMzgxLDM3OCwzNzQsMzcxLDM3MCwzNjcsMzYzLDM2MiwzNjEsMzYxLDM2NCwzNjcsMzY4LDM3MCwzNzAsMzY2LDM2MywzNjEsMzYxLDM2MSwzNjIsMzY1LDM2OSwzNzIsMzc0LDM3NCwzNzQsMzczLDM3MywzNzQsMzczLDM3NSwzNzcsMzc5LDM4MCwzODEsMzg0LDM4OCwzOTIsMzk0LDM5NSwzOTUsMzk3LDM5OCw0MDAsNDAxLDQwMyw0MDUsNDA3LDQwOSw0MTAsNDEwLDQxMSw0MTEsNDEyLDQxMyw0MTYsNDE5LDQyMiw0MjYsNDI5LDQzMiw0MzQsNDM0LDQzMiw0MzAsNDI3LDQyNCw0MjQsNDI1LDQyNyw0MjgsNDI4LDQyNyw0MjYsNDIzLDQyNiw0MjgsNDMwLDQyOSw0MjgsNDI5LDQyNyw0MjYsNDI2LDQyMyw0MjIsNDIxLDQxOSw0MjIsNDIxLDQyMiw0MjIsNDI1LDQyOCw0MzIsNDM1LDQzNyw0MzksNDQyLDQ0NCw0NDgsNDUwLDQ1Miw0NTYsNDU1LDQ1Niw0NTYsNDU3LDQ1OCw0NTcsNDU2LDQ1Niw0NTYsNDU4LDQ1Niw0NTUsNDU2LDQ1Niw0NTcsNDU4LDQ2MCw0NjEsNDYxLDQ2MSw0NjAsNDYwLDQ1OSw0NTgsNDU4LDQ1OCw0NTksNDYxLDQ2Myw0NjQsNDY2LDQ2OCw0NjgsNDY4LDQ3Miw0NzIsNDcyLDQ3Miw0NzIsNDcwLDQ2OSw0NjksNDY5LDQ2OCw0NzAsNDY5LDQ2Nyw0NjYsNDY1LDQ2OCw0NjgsNDY5LDQ3NSw0NzgsNDgyLDQ4MCw0NzgsNDc1LDQ3Myw0NzQsNDcyLDQ3Myw0NzMsNDcxLDQ3MSw0NjksNDY1LDQ2OCw0NzAsNDczLDQ3Niw0ODIsNDg5LDQ5Nyw1MDYsNTE0LDUyMCw1MjUsNTI3LDUyOCw1MjgsNTI2LDUyNSw1MjIsNTIyLDUyMyw1MjgsNTMyLDUzNSw1Mzc",
////                            lead2_data= base64String,
//                            first_name= "ZW5jcnlwdGVkIG5hbWU=",
//                            last_name= "ZW5jcnlwdGVkIG5hbWU=",
//                            age= "MzI=",
//                            height= "MzM=",
//                            weight= "MzM=",
//                            gender= "bWFsZQ==",
//                            generate_pdf_report= true,
//                            processor_type= "LEAD_TWO"
//                        ))
//
//                    )
//                    data.enqueue(object : Callback,
//                        retrofit2.Callback<ReportResponse> {
//                        override fun onResponse(
//                            call: Call<ReportResponse>,
//                            response: Response<ReportResponse>,
//                        ) {
//                            Log.d("Json.TAG", "data: ${response.body()}")
//                            runOnUiThread {
//                                Toast.makeText(this@LeadIITestActivity,response.body()?.image_url,Toast.LENGTH_SHORT).show()
//                                binding.textView.text = response.body()?.image_url
//                            }
//                        }
//
//                        override fun onFailure(call: Call<ReportResponse>, t: Throwable) {
//                            Log.d("Json.TAG", "onFailure: $t")
//                            runOnUiThread {
//                                Toast.makeText(this@LeadIITestActivity,t.message,Toast.LENGTH_SHORT).show()
//                            }
//                        }
//                    })
        if (ecgPoints != null) {
            this@LeadIITestActivity.ecgPoints[ecgPosition] = ecgPoints
        }
    }

    override fun onDeviceConnectionStateChanged(deviceConnectionState: DeviceConnectionState) {
        when (deviceConnectionState) {
            DeviceConnectionState.DISCONNECTED -> {
                binding.activityMainLayoutDeviceConnectionStatus.setBackgroundColor(Color.RED)
            }

            DeviceConnectionState.CONNECTED -> {}

            DeviceConnectionState.VERIFICATION_TIME_OUT -> {}
            DeviceConnectionState.USB_CONNECTION_PERMISSION_DENIED -> {}
        }
    }

    override fun onDeviceTypeChange(deviceType: String) {

    }

    override fun onDeviceVerified(deviceInfo: DeviceInfo) {
//        binding.activityMainLayoutDeviceConnectionStatus.setBackgroundColor(if (SeriCom.isDeviceConnected()) Color.GREEN else Color.RED)
    }
}